services:
  db:
    image: quay.io/tembo/pg16-pgmq@sha256:7f80d046257d585d1af9d19cf28bd355a4b854b0a7d643c02ebbe6b84457868a
    restart: always
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db8_test
    ports: ["54329:5432"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d db8_test"]
      interval: 5s
      timeout: 3s
      retries: 10
